//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_CarCheck
    {
        public string F_Id { get; set; }
        public string F_1 { get; set; }
        public string F_2 { get; set; }
        public string F_3 { get; set; }
        public string F_4 { get; set; }
        public string F_5 { get; set; }
        public Nullable<bool> F_6 { get; set; }
        public Nullable<bool> F_7 { get; set; }
        public Nullable<bool> F_8 { get; set; }
        public Nullable<bool> F_9 { get; set; }
        public Nullable<bool> F_10 { get; set; }
        public Nullable<bool> F_11 { get; set; }
        public Nullable<bool> F_12 { get; set; }
        public Nullable<bool> F_13 { get; set; }
        public Nullable<bool> F_14 { get; set; }
        public Nullable<bool> F_15 { get; set; }
        public Nullable<bool> F_16 { get; set; }
        public Nullable<bool> F_17 { get; set; }
        public Nullable<bool> F_18 { get; set; }
        public Nullable<bool> F_19 { get; set; }
        public Nullable<bool> F_20 { get; set; }
        public Nullable<bool> F_21 { get; set; }
        public Nullable<bool> F_22 { get; set; }
        public Nullable<bool> F_23 { get; set; }
        public Nullable<bool> F_24 { get; set; }
        public Nullable<bool> F_25 { get; set; }
        public Nullable<bool> F_26 { get; set; }
        public Nullable<bool> F_27 { get; set; }
        public Nullable<bool> F_28 { get; set; }
        public Nullable<bool> F_29 { get; set; }
        public Nullable<bool> F_30 { get; set; }
        public Nullable<bool> F_31 { get; set; }
        public Nullable<bool> F_32 { get; set; }
        public Nullable<bool> F_33 { get; set; }
        public Nullable<bool> F_34 { get; set; }
        public Nullable<bool> F_35 { get; set; }
        public Nullable<bool> F_36 { get; set; }
        public Nullable<bool> F_37 { get; set; }
        public Nullable<bool> F_38 { get; set; }
        public Nullable<bool> F_39 { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public string F_Remakes { get; set; }
    }
}
