//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Case
    {
        public string F_Id { get; set; }
        public string F_1 { get; set; }
        public string F_2 { get; set; }
        public string F_3 { get; set; }
        public string F_4 { get; set; }
        public string F_5 { get; set; }
        public string F_6 { get; set; }
        public string F_7 { get; set; }
        public string F_8 { get; set; }
        public string F_9 { get; set; }
        public string F_10 { get; set; }
        public string F_Remakes { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
    }
}
