//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeus.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Jdccy
    {
        public string F_Id { get; set; }
        public string 车牌号码 { get; set; }
        public string 号牌类型 { get; set; }
        public string 使用性质 { get; set; }
        public string 车身颜色下拉 { get; set; }
        public string 核定载人数下拉 { get; set; }
        public Nullable<bool> 注册登记 { get; set; }
        public Nullable<bool> 转入 { get; set; }
        public Nullable<bool> 转移登记 { get; set; }
        public Nullable<bool> 变更迁出 { get; set; }
        public Nullable<bool> 变更车身颜色 { get; set; }
        public Nullable<bool> 变更车身或车架 { get; set; }
        public Nullable<bool> 变更发动机 { get; set; }
        public Nullable<bool> 变更使用性质 { get; set; }
        public Nullable<bool> 重新打刻VIN { get; set; }
        public Nullable<bool> 重新打刻发动机号 { get; set; }
        public Nullable<bool> 加装拆除操纵辅助装置 { get; set; }
        public Nullable<bool> 更换整车 { get; set; }
        public Nullable<bool> 申领登记证书 { get; set; }
        public Nullable<bool> 补领登记证书 { get; set; }
        public Nullable<bool> 监销 { get; set; }
        public Nullable<bool> 其他 { get; set; }
        public Nullable<bool> 车辆识别代号 { get; set; }
        public Nullable<bool> 发动机型号号码 { get; set; }
        public Nullable<bool> 车身品牌型号 { get; set; }
        public Nullable<bool> 车辆类型 { get; set; }
        public Nullable<bool> 号牌车辆外观形状 { get; set; }
        public Nullable<bool> 轮胎完好情况 { get; set; }
        public Nullable<bool> 安全带三角警告牌 { get; set; }
        public Nullable<bool> 外廊尺寸轴数 { get; set; }
        public Nullable<bool> 整备质量 { get; set; }
        public Nullable<bool> 轮胎规格 { get; set; }
        public Nullable<bool> 侧后部防护装置 { get; set; }
        public Nullable<bool> 车身反光标识 { get; set; }
        public Nullable<bool> 灭火器 { get; set; }
        public Nullable<bool> 行驶记录装置车内外录像监控装置 { get; set; }
        public Nullable<bool> 应急出口应急锤乘客门 { get; set; }
        public Nullable<bool> 外部标识文字喷涂 { get; set; }
        public Nullable<bool> 标志灯具警报器 { get; set; }
        public Nullable<bool> 检验合格证明 { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
    }
}
