
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Zeus.Model
{

using System;
    using System.Collections.Generic;
    
public partial class A_Receivables
{

    public string F_Id { get; set; }

    public string F_SKDH { get; set; }

    public string F_CLLX { get; set; }

    public string F_CLLB { get; set; }

    public Nullable<bool> F_MH { get; set; }

    public Nullable<bool> F_MZ { get; set; }

    public Nullable<bool> F_ZX { get; set; }

    public Nullable<bool> F_ZZL { get; set; }

    public Nullable<bool> F_KDH { get; set; }

    public Nullable<bool> F_RS { get; set; }

    public Nullable<decimal> F_SFJE { get; set; }

    public string F_JEDX { get; set; }

    public string F_SKRY { get; set; }

    public string F_JKRY { get; set; }

    public Nullable<bool> F_JZZT { get; set; }

    public Nullable<System.DateTime> F_HKSJ { get; set; }

    public Nullable<bool> F_ZFZT { get; set; }

    public Nullable<System.DateTime> F_CreatorTime { get; set; }

    public string F_CreatorUserId { get; set; }

    public Nullable<System.DateTime> F_LastModifyTime { get; set; }

    public string F_LastModifyUserId { get; set; }

    public Nullable<System.DateTime> F_DeleteTime { get; set; }

    public string F_DeleteUserId { get; set; }

    public Nullable<bool> F_DeleteMark { get; set; }

    public string F_Remakes { get; set; }

}

}
