

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace Zeus.Model
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ZeusEntities : DbContext
{
    public ZeusEntities()
        : base("name=ZeusEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Sys_Area> Sys_Area { get; set; }

    public virtual DbSet<Sys_DbBackup> Sys_DbBackup { get; set; }

    public virtual DbSet<Sys_FilterIP> Sys_FilterIP { get; set; }

    public virtual DbSet<Sys_Items> Sys_Items { get; set; }

    public virtual DbSet<Sys_ItemsDetail> Sys_ItemsDetail { get; set; }

    public virtual DbSet<Sys_Log> Sys_Log { get; set; }

    public virtual DbSet<Sys_Module> Sys_Module { get; set; }

    public virtual DbSet<Sys_ModuleButton> Sys_ModuleButton { get; set; }

    public virtual DbSet<Sys_Organize> Sys_Organize { get; set; }

    public virtual DbSet<Sys_Role> Sys_Role { get; set; }

    public virtual DbSet<Sys_RoleAuthorize> Sys_RoleAuthorize { get; set; }

    public virtual DbSet<Sys_User> Sys_User { get; set; }

    public virtual DbSet<Sys_UserLogOn> Sys_UserLogOn { get; set; }

    public virtual DbSet<A_CarCheck> A_CarCheck { get; set; }

    public virtual DbSet<A_Receivables> A_Receivables { get; set; }

}

}

